# $Id: GNUmakefile,v 1.14 1994/11/30 02:38:06 vertex Exp $
# GNUmakefile for Portfolio Include Files
#
# Copyright (c) 1992, 1993, The 3DO Company, Inc.
# All rights reserved.
# This document is proprietary and confidential

default:		all

DOCS=			IncludesChangeLog.doc

# It would be nice, someday, to apportion responsibility for these
# files to the packages that export them.

# This list may not be complete -- it is the bare minimum set of
# header files that must be added to make the build work.

INCS_HERE= \
	debug.h \
	cplusswi.h \
	cplusswi_redfn.h \
	hardware.i \
	inthard.h \
	inthard.i \
	limits.h \
	madam.h \
	manuids.h \
	rom.h \
	scanf.h \
	setjmp.h \
	stdlib.h \
	structs.i \
	super.h \
	varargs_glue.h

DEPFILE=	.autodepends
include GNUmakefile.master
