# $Id: GNUmakefile,v 1.3 1994/12/09 01:22:25 vertex Exp $
# GNUmakefile for the International folio and related objects.
#
# Copyright (c) 1994, The 3DO Company, Inc.
# All Rights Reserved.
# This document is proprietary and confidential

default: all


###############################################################################
# Describe our files
#
BDIRS    = lib folio drivers utilities tests

DOCS     = IntlFolioNotes.doc

DEPFILE  = .autodepends

include GNUmakefile.master
