# $Id: GNUmakefile,v 1.2 1994/10/07 15:59:09 vertex Exp $
# GNUmakefile for the compression folio and related objects.
#
# Copyright (c) 1994, The 3DO Company, Inc.
# All Rights Reserved.
# This document is proprietary and confidential

default: all


###############################################################################
# Describe our files
#
BDIRS    = lib folio

DOCS     = CompressionFolioNotes.doc

DEPFILE  = .autodepends

include GNUmakefile.master
