# $Id: GNUmakefile,v 1.1 1994/08/24 20:25:17 vertex Exp $
# GNUmakefile for the JString folio and related objects.
#
# Copyright (c) 1994, The 3DO Company, Inc.
# All Rights Reserved.
# This document is proprietary and confidential

default: all


###############################################################################
# Describe our files
#
BDIRS    = lib folio

DOCS     = JStringFolioNotes.doc

DEPFILE  = .autodepends

include GNUmakefile.master
