# $Id: GNUmakefile,v 1.1 1994/06/29 23:17:34 vertex Exp $
# GNUmakefile for the Debugger folio and related objects.
#
# Copyright (c) 1994, The 3DO Company, Inc.
# All Rights Reserved.
# This document is proprietary and confidential

default: all


###############################################################################
# Describe our files
#
BDIRS    = lib folio test

DOCS     =

DEPFILE  = .autodepends

include GNUmakefile.master
