; DO NOT EDIT THIS FILE
; This file was generated by ./make_pakhdr.sh on Thu Mar  2 20:37:37 PST 1995.
; This is the header for a dipir driver package.

 AREA |ASMCODE|, CODE, READONLY
 DCD &925fbcd0 ; Magic number for PACK file (PACK_MAGIC)
 DCD 6 ; number of drivers
; -- creative/enc/icddipir --
 DCW &1000 ; manufacturer id
 DCW &F000 ; manufacturer device number
 DCD 80 ; offset of start of driver
 DCD 8432 ; size of driver
; -- meidev.drv --
 DCW &0010 ; manufacturer id
 DCW &0001 ; manufacturer device number
 DCD 8512 ; offset of start of driver
 DCD 2092 ; size of driver
; -- fmvdev.drv --
 DCW &1000 ; manufacturer id
 DCW &0020 ; manufacturer device number
 DCD 10604 ; offset of start of driver
 DCD 1032 ; size of driver
; -- mei563dev.drv --
 DCW &0010 ; manufacturer id
 DCW &0563 ; manufacturer device number
 DCD 11636 ; offset of start of driver
 DCD 2036 ; size of driver
; -- lccddev.drv --
 DCW &1000 ; manufacturer id
 DCW &0050 ; manufacturer device number
 DCD 13672 ; offset of start of driver
 DCD 7104 ; size of driver
; -- depotdev.drv --
 DCW &1000 ; manufacturer id
 DCW &0030 ; manufacturer device number
 DCD 20776 ; offset of start of driver
 DCD 1712 ; size of driver
 END
